### ISSUE TITLE
serde_untagged_optional doesn't handle when field does not exist. 

### ISSUE THREAD

**Issue by SpyMachine** [bluss/either#52]
Hi, not sure if there's a good way to handle this, but I wanted to use Option like I usually do in serde where if the field does not exist it is None, however this is not how it works here:

```
use serde::{Deserialize};
use either::Either;

#[derive(Deserialize, Debug)]
struct Test {
    #[serde(with = "either::serde_untagged_optional")]
    field: Option<Either<String, Vec<String>>>,
    another_field: u32,
}

fn main() {
    // deserialization
    let data: Test = serde_json::from_str(
        r#"{"another_field": 6}"#
    ).unwrap();
    println!("found {:?}", data);
}
```
This panics because field is not found.

I've worked around this issue by just having a container struct for that particular field and just use either::serde_untagged but was just curious if this was intended behavior or not.

```
#[derive(Deserialize, Debug)]
struct Container(#[serde(with = "either::serde_untagged")] Either<String, Vec<String>>);

#[derive(Deserialize, Debug)]
struct Test {
    field: Option<Container>,
    another_field: u32,
}
```

**Comment by cuviper** [comment]
Looking at `cargo expand`, it seems that serde generates a call to [`serde::private::de::missing_field`](https://github.com/serde-rs/serde/blob/0e1c4093c857d4550573386a1da907707ca6af17/serde/src/private/de.rs#L15-L17) for unannotated fields, which sets `None` if the type is any `Option<T>`. However, it doesn't have this fallback when `#[serde(with = "...")]` is used -- maybe that's a serde bug?

I don't think there's anything that we can do about that here in `either`, because our custom code is never called if there's no field. From your side, you can use `#[serde(default, with = "...")]` to get around this.

**Comment by SpyMachine** [comment]
Heh, yeah was just playing on my own and was going to come back here with the same solution 👍
